from app.forms.login_form import LoginForm
from app.forms.signup_form import SignUpForm
from app.forms.create_post import CreatePost
from app.forms.create_comment import CreateComment
from app.forms.create_retailer import CreateRetailer
from app.forms.create_retailer_rating import CreateRetailerRating
from app.forms.create_community import CreateCommunity
from app.forms.create_post_rating import CreatePostRating
from app.forms.create_meetup import CreateMeetup
from app.forms.create_comment_rating import CreateCommentRating
