"""create lat and lng on meetups

Revision ID: 3fc0203ff0f0
Revises: e3919cd21c9b
Create Date: 2021-03-22 21:13:05.056978

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '3fc0203ff0f0'
down_revision = 'e3919cd21c9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetups', sa.Column('lat', sa.Numeric(scale=7), nullable=True))
    op.add_column('meetups', sa.Column('lng', sa.Numeric(scale=7), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetups', 'lng')
    op.drop_column('meetups', 'lat')
    # ### end Alembic commands ###
