"""update comments model

Revision ID: 32b61a573ad8
Revises: f1ba629b1857
Create Date: 2021-03-05 15:19:00.691588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32b61a573ad8'
down_revision = 'f1ba629b1857'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'comment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'comment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
