"""add lat and lng columns to retailer

Revision ID: e3919cd21c9b
Revises: 32b61a573ad8
Create Date: 2021-03-12 13:32:51.555136

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'e3919cd21c9b'
down_revision = '32b61a573ad8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('retailers', sa.Column('lat', sa.Numeric(scale=7), nullable=True))
    op.add_column('retailers', sa.Column('lng', sa.Numeric(scale=7), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('retailers', 'lng')
    op.drop_column('retailers', 'lat')
    # ### end Alembic commands ###
