name: Build Test

on:
  pull_request:
    branches: [staging]
    paths:
      - "react-app/**"

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: react-app

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: react-app/package-lock.json
      # This isn't my best idea...
      - run: npm install --force
      - run: npm run build --if-present
