name: Push Container to Heroku - Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy-staging:
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: staging
      - name: Log into the Heroku Container Registry
        run: heroku container:login
      - name: Build and push image
        run: heroku container:push -a qwerkey-staging web
      - name: Release image
        run: heroku container:release -a qwerkey-staging web
