name: "Pre-Commit Check"
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
env:
  PYTHON_VERSION: 3.11
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ env.PYTHON_VERSION }}-${{ hashFiles('.pre-commit-config.yaml') }}
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - uses: pre-commit/action@v2.0.2
