# This is a basic workflow to help you get started with Actions

name: Pytest

on:
  pull_request:
    branches: [staging]
    paths:
      - "app/**"
      - "api/**"
      - "Pipfile*"
      - "*requirements.txt"

jobs:
  pytest:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      S3_BUCKET_NAME: test
      S3_ACCESS_KEY: test
      S3_SECRET_ACCESS_KEY: test
      DATABASE_URL: "postgresql://test:test@localhost/test"
      OPEN_CAGE_API_KEY: test

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run pytest
        run: pytest
