# This is a basic workflow to help you get started with Actions

name: Pytest

on:
  pull_request:
    branches: [staging]
    paths:
      - "app/**"

jobs:
  pytest:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run pytest
        run: pytest
